---
version: "3"
set:
  - pipefail
shopt:
  - globstar

includes:
  darwin: .taskfiles/darwin/Taskfile.yaml
  nixos: .taskfiles/nixos/Taskfile.yaml
  sops: .taskfiles/sops/Taskfile.yaml

tasks:
  default:
    silent: true
    cmds:
      - task -l
