set quiet := true
set shell := ['bash', '-euo', 'pipefail', '-c']

ROOT_DIR := invocation_directory()

[private]
default:
  @just --list nixos

[doc('Build nixos configuration, HOST required')]
build HOST: (_operation build HOST)

[doc('Switch nixos configuration, HOST required')]
switch HOST: (_operation switch HOST)

_operation OPERATION HOST:
  # Check that OPERATION is either 'build' or 'switch'
  @if [ "{{OPERATION}}" != "build" ] && [ "{{OPERATION}}" != "switch" ]; then \
    echo "OPERATION must be 'build' or 'switch'" && exit 1; \
  fi
  nix-shell -p nixos-rebuild --run "nixos-rebuild {{OPERATION}} --flake {{ROOT_DIR}}/.#{{HOST}}"
