# This file was autogenerated. DO NOT EDIT!
{
  version = "v2.8.4";
  cfVersion = "v0.0.0-20240703190432-89f16b99c18e";
  vendorHash = "sha256-pLyb25XMpn0e/f3qFechwq23P2hXvdfzLp12EkgIEmg=";
  dist = {
    owner = "caddyserver";
    repo = "dist";
    rev = "v2.8.4";
    hash = "sha256-O4s7PhSUTXoNEIi+zYASx8AgClMC5rs7se863G6w+l0=";
  };
}
