# This file was autogenerated. DO NOT EDIT!
{
  version = "v2.9.0";
  cfVersion = "v0.0.0-20240703190432-89f16b99c18e";
  vendorHash = "sha256-3QcpmPUhZZ8oN/CUbCh/A1D0B59o1RxWPyMbA/WoRcU=";
  dist = {
    owner = "caddyserver";
    repo = "dist";
    rev = "v2.9.0";
    hash = "";
  };
}
