[mattermost]
[mattermost.homelab]
Server="${MATTERMOST_SVR}"
Team="${MATTERMOST_TEAM}"
Login="${MATTERMOST_LOGIN}"
Password="${MATTERMOST_PASS}"

[discord]
[discord.main]
Server="${DISCORD_SVR}"
Token="${DISCORD_TOKEN}"

[[gateway]]
name="discord"
enable=true
[[gateway.inout]]
account="discord.main"
channel="general"
[[gateway.inout]]
account="mattermost.homelab"
channel="general"