---
version: "3"

tasks:
  darwin-deploy:
    desc: Build and apply nix-darwin configuration
    silent: true
    summary: |
      Args:
        HOST: Host to build and deploy to (required)
    requires:
      vars:
        - HOST
    cmds:
      - task: darwin-build
        vars:
          HOST: "{{ .HOST }}"
      - task: _prompt_to_continue
      - darwin-rebuild switch --flake "{{.ROOT_DIR}}/#{{.HOST}}"
    preconditions:
      - sh: which nix
        msg: "nix not found"
      - sh: which darwin-rebuild
        msg: "darwin-rebuild not found"

  darwin-build:
    desc: Build nix-darwin configuration
    silent: true
    summary: |
      Args:
        HOST: Host to build and deploy to (required)
    requires:
      vars:
        - HOST
    cmds:
      - darwin-rebuild build --flake "{{.ROOT_DIR}}/#{{.HOST}}"
      - nvd diff /run/current-system result
    preconditions:
      - sh: which nix
        msg: "nix not found"
      - sh: which darwin-rebuild
        msg: "darwin-rebuild not found"

  nixos-build:
    desc: Build nixos configuration
    silent: true
    vars:
      SSH_USER: soulwhisper
    summary: |
      Args:
        HOST: Host to build and deploy to (required)
    requires:
      vars:
        - HOST
    cmds:
      - nix-shell -p nixos-rebuild --run 'nixos-rebuild build --flake .#{{.HOST}} --fast --use-remote-sudo --build-HOST "{{.SSH_USER}}@{{.HOST}}.homelab.internal" --target-HOST "{{.SSH_USER}}@{{.HOST}}.homelab.internal"'
    preconditions:
      - sh: which nix
        msg: "nix not found"
      - sh: which nixos-rebuild
        msg: "nixos-rebuild not found"

  nixos-deploy:
    desc: Build and apply nixos configuration
    silent: true
    vars:
      SSH_USER: soulwhisper
    summary: |
      Args:
        HOST: Host to build and deploy to (required)
    requires:
      vars:
        - HOST
    cmds:
      - nix-shell -p nixos-rebuild --run 'nixos-rebuild switch --flake .#{{.HOST}} --fast --use-remote-sudo --build-HOST "{{.SSH_USER}}@{{.HOST}}.homelab.internal" --target-HOST "{{.SSH_USER}}@{{.HOST}}.homelab.internal"'
    preconditions:
      - sh: which nix
        msg: "nix not found"
      - sh: which nixos-rebuild
        msg: "nixos-rebuild not found"

  _prompt_to_continue:
    internal: true
    prompt: Do you want to continue applying this configuration?
