---
version: "3"

# Notice: nix-darwin needs 'sudo' since 25.05
tasks:
  init:
    desc: Initialize nix-darwin configuration if darwin-rebuild not exist
    silent: true
    vars:
      HOST: '{{.HOST | default "soulwhisper-mba"}}'
    preconditions:
      - which nix
    cmds:
      - |
        # fix ca-certificates issue
        # sudo rm -f /etc/ssl/certs/ca-certificates.crt
        # sudo ln -s /nix/var/nix/profiles/default/etc/ssl/certs/ca-bundle.crt /etc/ssl/certs/ca-certificates.crt
      - sudo nix --extra-experimental-features 'nix-command flakes' run nix-darwin/master#darwin-rebuild -- switch --flake "{{.ROOT_DIR}}/#{{.HOST}}"

  build:
    desc: Build nix-darwin configuration
    silent: true
    vars:
      HOST: '{{.HOST | default "soulwhisper-mba"}}'
    preconditions:
      - which darwin-rebuild nvd
    cmds:
      - sudo darwin-rebuild build --flake "{{.ROOT_DIR}}/#{{.HOST}}"
      - sudo nvd diff /run/current-system result

  switch:
    desc: Switch nix-darwin configuration
    silent: true
    vars:
      HOST: '{{.HOST | default "soulwhisper-mba"}}'
    preconditions:
      - which darwin-rebuild
    cmds:
      - sudo darwin-rebuild switch --flake "{{.ROOT_DIR}}/#{{.HOST}}"
