---
version: "3"

tasks:
  "*":
    desc: Build/Switch nixos configuration with multi-mode support [HOST=required]
    silent: true
    vars:
      OPERATION: "{{index .MATCH 0}}"
      BUILDER: '{{.BUILDER | default "disabled"}}'
    requires:
      vars:
        - HOST
    preconditions:
      - '[[ "{{.OPERATION}}" == "build" || "{{.OPERATION}}" == "switch" ]]'
      - which nix
    cmds:
      - nix-shell -p nixos-rebuild --run 'nixos-rebuild {{.OPERATION}}
        --flake {{.ROOT_DIR}}/.#{{.HOST}}
        {{ if ne .BUILDER "disabled"}}
        --build-host "{{.BUILDER}}"
        --target-host "{{.HOST}}"
        --use-remote-sudo --fast
        {{ end }}'
