# this is an example
web:
  address: 0.0.0.0
  port: 9801

storage:
  type: sqlite
  path: /etc/gatus/data.db

endpoints:
  - name: minio
    group: internal
    url: "https://s3.${EXT-DOMAIN}"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"

  - name: k8s-endpoints
    group: internal
    url: "http://k8s.${INT-DOMAIN}"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: nas
    group: internal
    url: "http://nas.${INT-DOMAIN}"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: cf-dns-check
    group: external
    url: "1.1.1.1"
    interval: 5m
    dns:
      query-name: "baidu.com"
      query-type: "A"
    conditions:
      - "[BODY] == 39.156.66.10"
      - "[DNS_RCODE] == NOERROR"

  - name: router-ping
    group: icmp-ping
    url: "icmp://1.0.0.1"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
