# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  caddy-core = {
    pname = "caddy-core";
    version = "v2.11.1";
    src = fetchFromGitHub {
      owner = "caddyserver";
      repo = "caddy";
      rev = "v2.11.1";
      fetchSubmodules = false;
      sha256 = "sha256-8NvRodMtq9Yrock7QRvF6ZOjuqpiK0KS3UeJzYcIbsg=";
    };
  };
  caddy-plugin-cloudflare = {
    pname = "caddy-plugin-cloudflare";
    version = "6dc1fbb7e925b0da6736780db2e90f4816b79ab7";
    src = fetchFromGitHub {
      owner = "caddy-dns";
      repo = "cloudflare";
      rev = "6dc1fbb7e925b0da6736780db2e90f4816b79ab7";
      fetchSubmodules = false;
      sha256 = "sha256-/FB0a/Ja4kDSw9SlNiusi6w7r87xHXafzEOQqLbTsyA=";
    };
    date = "2025-12-04";
  };
  hass-sgcc = {
    pname = "hass-sgcc";
    version = "v1.7.1";
    src = fetchFromGitHub {
      owner = "ARC-MX";
      repo = "sgcc_electricity_new";
      rev = "v1.7.1";
      fetchSubmodules = false;
      sha256 = "sha256-dHT24tdFXT5dyv6KSI9fISxCRA7CTgyJJXSHNxHxkSI=";
    };
  };
  kubecolor-catppuccin = {
    pname = "kubecolor-catppuccin";
    version = "1d4c2888f7de077e1a837a914a1824873d16762d";
    src = fetchFromGitHub {
      owner = "vkhitrin";
      repo = "kubecolor-catppuccin";
      rev = "1d4c2888f7de077e1a837a914a1824873d16762d";
      fetchSubmodules = false;
      sha256 = "sha256-gTneUh6yMcH6dVKrH00G61a+apasu9tiMyYjvNdOiOw=";
    };
    date = "2024-05-24";
  };
  kubectl-switch = {
    pname = "kubectl-switch";
    version = "v2.4.8";
    src = fetchFromGitHub {
      owner = "mirceanton";
      repo = "kubectl-switch";
      rev = "v2.4.8";
      fetchSubmodules = false;
      sha256 = "sha256-Nv03pvl0QQJ07bcZ+P4wAAU64XQNsSLPGKYSCsg3VS4=";
    };
  };
  rime-moqi-yinxing = {
    pname = "rime-moqi-yinxing";
    version = "db7bc4e9c8eb7cbff51e61dcc76f1d88d0255343";
    src = fetchFromGitHub {
      owner = "gaboolic";
      repo = "rime-shuangpin-fuzhuma";
      rev = "db7bc4e9c8eb7cbff51e61dcc76f1d88d0255343";
      fetchSubmodules = false;
      sha256 = "sha256-39STMvHWcix3C11ZXUicEXg1wa8sj4KinVY3aMQHYE4=";
    };
    date = "2026-02-15";
  };
  talos-api = {
    pname = "talos-api";
    version = "v1.0.15";
    src = fetchFromGitHub {
      owner = "siderolabs";
      repo = "discovery-service";
      rev = "v1.0.15";
      fetchSubmodules = false;
      sha256 = "sha256-AI1jBsS/JuCSsCr69dfwQQpucbEvXpMxFDq+UoRUlJk=";
    };
  };
  zotregistry = {
    pname = "zotregistry";
    version = "v2.1.14";
    src = fetchFromGitHub {
      owner = "project-zot";
      repo = "zot";
      rev = "v2.1.14";
      fetchSubmodules = false;
      sha256 = "sha256-ecTgRt8qrG0T2TI95RXIiCWaTuogjGElhaS2NFnRQXI=";
    };
  };
  zotregistry-ui = {
    pname = "zotregistry-ui";
    version = "111cb8e40e5e3dd4e9641820e8795a13c19b8154";
    src = fetchFromGitHub {
      owner = "project-zot";
      repo = "zui";
      rev = "111cb8e40e5e3dd4e9641820e8795a13c19b8154";
      fetchSubmodules = false;
      sha256 = "sha256-WjOBnINKwHb/B9iweg3Tt2Jdbg4jFgjE7lGJ57X6hF4=";
    };
    date = "2026-02-21";
  };
}
