# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  caddy-core = {
    pname = "caddy-core";
    version = "v2.11.4";
    src = fetchFromGitHub {
      owner = "caddyserver";
      repo = "caddy";
      rev = "v2.11.4";
      fetchSubmodules = false;
      sha256 = "sha256-wzk8KRZfDCbbjRlBwkoKAoMjOhV4xF3yuXUueqtl1xM=";
    };
  };
  caddy-plugin-cloudflare = {
    pname = "caddy-plugin-cloudflare";
    version = "a8737d095ad5a48ca031cea6ab704057dbc2d250";
    src = fetchFromGitHub {
      owner = "caddy-dns";
      repo = "cloudflare";
      rev = "a8737d095ad5a48ca031cea6ab704057dbc2d250";
      fetchSubmodules = false;
      sha256 = "sha256-0Csi6WmyoGj7bXeo2Lrnwr0SCoV6c/niymtOp5DdiT4=";
    };
    date = "2026-03-23";
  };
  hass-sgcc = {
    pname = "hass-sgcc";
    version = "v1.8.0";
    src = fetchFromGitHub {
      owner = "ARC-MX";
      repo = "sgcc_electricity_new";
      rev = "v1.8.0";
      fetchSubmodules = false;
      sha256 = "sha256-edic+4yEWWvReLtCf9y82fkLiBB+hvOjK6gysQ9tcIw=";
    };
  };
  kubecolor-catppuccin = {
    pname = "kubecolor-catppuccin";
    version = "1d4c2888f7de077e1a837a914a1824873d16762d";
    src = fetchFromGitHub {
      owner = "vkhitrin";
      repo = "kubecolor-catppuccin";
      rev = "1d4c2888f7de077e1a837a914a1824873d16762d";
      fetchSubmodules = false;
      sha256 = "sha256-gTneUh6yMcH6dVKrH00G61a+apasu9tiMyYjvNdOiOw=";
    };
    date = "2024-05-24";
  };
  kubectl-switch = {
    pname = "kubectl-switch";
    version = "v2.4.8";
    src = fetchFromGitHub {
      owner = "mirceanton";
      repo = "kubectl-switch";
      rev = "v2.4.8";
      fetchSubmodules = false;
      sha256 = "sha256-Nv03pvl0QQJ07bcZ+P4wAAU64XQNsSLPGKYSCsg3VS4=";
    };
  };
  rime-moqi-yinxing = {
    pname = "rime-moqi-yinxing";
    version = "0991dfdca02f9c89c856abeb83f32da8fd7885cd";
    src = fetchFromGitHub {
      owner = "gaboolic";
      repo = "rime-shuangpin-fuzhuma";
      rev = "0991dfdca02f9c89c856abeb83f32da8fd7885cd";
      fetchSubmodules = false;
      sha256 = "sha256-+mmbb3/qoNSHe8+RmkFezr2x+5t+2hYqQ0FqgGxsRgM=";
    };
    date = "2026-07-09";
  };
  talos-api = {
    pname = "talos-api";
    version = "v1.0.17";
    src = fetchFromGitHub {
      owner = "siderolabs";
      repo = "discovery-service";
      rev = "v1.0.17";
      fetchSubmodules = false;
      sha256 = "sha256-hW7N3vKqvWlFHizOT6rlzNZyG6q7h0z5Fv8zavH5AQ4=";
    };
  };
  zotregistry = {
    pname = "zotregistry";
    version = "v2.1.18";
    src = fetchFromGitHub {
      owner = "project-zot";
      repo = "zot";
      rev = "v2.1.18";
      fetchSubmodules = false;
      sha256 = "sha256-cYH+4nvrdtKRYx3bap8Ndhu8MtwOWQREnmCa7NE/+O8=";
    };
  };
  zotregistry-ui = {
    pname = "zotregistry-ui";
    version = "22d742d8aef2b628a5b4df5970a588eb7b22f1bf";
    src = fetchFromGitHub {
      owner = "project-zot";
      repo = "zui";
      rev = "22d742d8aef2b628a5b4df5970a588eb7b22f1bf";
      fetchSubmodules = false;
      sha256 = "sha256-W31GeAyW9yT/nj9GKyZjcBN1jhfdB1Vay4ujj8Ydiek=";
    };
    date = "2026-07-03";
  };
}
