# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  caddy-core = {
    pname = "caddy-core";
    version = "v2.11.7";
    src = fetchFromGitHub {
      owner = "caddyserver";
      repo = "caddy";
      rev = "v2.11.7";
      fetchSubmodules = false;
      sha256 = "sha256-6+USPwF6LzDWUjrNRL2ncxSz5KmqJM0L/6o03Lh8YD8=";
    };
  };
  caddy-plugin-cloudflare = {
    pname = "caddy-plugin-cloudflare";
    version = "a8737d095ad5a48ca031cea6ab704057dbc2d250";
    src = fetchFromGitHub {
      owner = "caddy-dns";
      repo = "cloudflare";
      rev = "a8737d095ad5a48ca031cea6ab704057dbc2d250";
      fetchSubmodules = false;
      sha256 = "sha256-0Csi6WmyoGj7bXeo2Lrnwr0SCoV6c/niymtOp5DdiT4=";
    };
    date = "2026-03-23";
  };
  dots-hyprland = {
    pname = "dots-hyprland";
    version = "547836f1b01a45445cfbbcd92b206d1b5ceee4d9";
    src = fetchFromGitHub {
      owner = "end-4";
      repo = "dots-hyprland";
      rev = "547836f1b01a45445cfbbcd92b206d1b5ceee4d9";
      fetchSubmodules = false;
      sha256 = "sha256-++80waGoDrql8s4iS4E3HCf5dZORy0GSLVyJNsI7+9Y=";
    };
    date = "2026-09-28";
  };
  inir = {
    pname = "inir";
    version = "v2.32.0";
    src = fetchFromGitHub {
      owner = "snowarch";
      repo = "iNiR";
      rev = "v2.32.0";
      fetchSubmodules = false;
      sha256 = "sha256-y9J2hr4w58FSDxo4XPN71/PhhcWlqbJaU7LQWVAoCnc=";
    };
  };
  kubecolor-catppuccin = {
    pname = "kubecolor-catppuccin";
    version = "1d4c2888f7de077e1a837a914a1824873d16762d";
    src = fetchFromGitHub {
      owner = "vkhitrin";
      repo = "kubecolor-catppuccin";
      rev = "1d4c2888f7de077e1a837a914a1824873d16762d";
      fetchSubmodules = false;
      sha256 = "sha256-gTneUh6yMcH6dVKrH00G61a+apasu9tiMyYjvNdOiOw=";
    };
    date = "2024-05-24";
  };
  kubectl-switch = {
    pname = "kubectl-switch";
    version = "v2.4.8";
    src = fetchFromGitHub {
      owner = "mirceanton";
      repo = "kubectl-switch";
      rev = "v2.4.8";
      fetchSubmodules = false;
      sha256 = "sha256-Nv03pvl0QQJ07bcZ+P4wAAU64XQNsSLPGKYSCsg3VS4=";
    };
  };
  rime-moqi-yinxing = {
    pname = "rime-moqi-yinxing";
    version = "c7c6de782c14c27541f7a8ce12be900f1f046f43";
    src = fetchFromGitHub {
      owner = "gaboolic";
      repo = "rime-shuangpin-fuzhuma";
      rev = "c7c6de782c14c27541f7a8ce12be900f1f046f43";
      fetchSubmodules = false;
      sha256 = "sha256-rhWu8LOF0ATHGTOzG83hcU8ODdQ+DQf5ruwOU9WWvQ0=";
    };
    date = "2026-09-22";
  };
  talos-api = {
    pname = "talos-api";
    version = "v1.1.2";
    src = fetchFromGitHub {
      owner = "siderolabs";
      repo = "discovery-service";
      rev = "v1.1.2";
      fetchSubmodules = false;
      sha256 = "sha256-kL6OUmlhDZSoVWHnnT+vewcnAdFlGLxADpNkfEmSBRI=";
    };
  };
}
