---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Auto-Lint-Fixer

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  auto-lint-fixer:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@0d564482f06ca65fa9e77e2510873638c82206f2 # v1
        id: app-token
        with:
          app-id: ${{ secrets.LAB_ASSISTANT_APP_ID }}
          private-key: ${{ secrets.LAB_ASSISTANT_APP_KEY }}
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: main
          fetch-depth: 0
      - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
      - uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Run devenv tests
        run: devenv test
      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(lint): fix linting issues"
          commit_user_name: "repo-butler[bot]"
          commit_user_email: "repo-butler[bot]@users.noreply.github.com"
          commit_author: "repo-butler[bot]"
