---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Auto-Lint-Fixer

# this action will trigger PR for fix, if lint fails

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  auto-lint-fixer:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@0d564482f06ca65fa9e77e2510873638c82206f2 # v1
        id: app-token
        with:
          app-id: ${{ secrets.LAB_ASSISTANT_APP_ID }}
          private-key: ${{ secrets.LAB_ASSISTANT_APP_KEY }}
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
      - uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Run devenv tests
        id: devenv-test
        continue-on-error: true
        run: devenv test
      - name: Create Pull
        id: create-pull-request
        uses: peter-evans/create-pull-request@dd2324fc52d5d43c699a5636bcf19fceaa70c284 # v7
        with:
          token: ${{ steps.app-token.outputs.token }}
          title: "chore(lint): fix linting issues"
          commit-message: "chore(lint): fix linting issues"
          delete-branch: true
