---
name: Flake update

# this workflow enabled until flake-parts fix renovate
# ref: https://github.com/hercules-ci/flake-parts/issues/277
# renovate also seems broken

on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 1 * * *

jobs:
  update-flakes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d # v16
      - name: Update flakes
        id: update-flakes
        run: |
          nix flake update
      - name: Generate Token
        uses: actions/create-github-app-token@af35edadc00be37caa72ed9f3e6d5f7801bfdf09 # v1
        id: app-token
        with:
          app-id: ${{ secrets.LAB_ASSISTANT_APP_ID }}
          private-key: ${{ secrets.LAB_ASSISTANT_APP_KEY }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7
        with:
          token: ${{ steps.app-token.outputs.token }}
          title: "chore(deps): Update nix flakes"
          commit-message: "chore(deps): Update nix flakes"
          body: |
            ## Summary
            ${{ steps.update-flakes.outputs }}
          add-paths: |
            flake.lock
          delete-branch: true
