---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Linter

# without specific token, this action will not trigger other workflow runs.

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v20
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Run devenv tests
        continue-on-error: true
        run: devenv test --verbose
      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79 # v5
        with:
          commit_message: "chore(lint): fix linting issues"
