---
name: Build and diff Nix systems

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'github/workflows/**'
      - '**.nix'
      - '!devenv.nix'
      - 'flake.lock'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  nix-build:
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'push' && github.event.head_commit.committer.username != 'web-flow')
    permissions:
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - system: soulwhisper-mba
            os: macos-latest
          - system: nix-dev
            os: ubuntu-latest
          - system: nix-infra
            os: ubuntu-latest
          - system: nix-nas
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: main
          fetch-depth: 0
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d # v16
        # with:
        #   source-tag: "v0.32.3"   # bugfixed
      # - name: Set up Magic Nix Cache # deprecated since 20250201
      #  uses: DeterminateSystems/magic-nix-cache-action@6221693898146dc97e38ad0e013488a16477a4c4 # v9
      - name: Set up Cachix
        uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
        if: ${{ !github.event.pull_request.head.repo.fork }}
        with:
          name: soulwhisper
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Garbage collect build dependencies
        run: nix-collect-garbage

      - name: Build previous ${{ matrix.system }} system
        run: |
          nix build \
            "github:soulwhisper/nix-config#ciSystems.${{ matrix.system }}" \
            --profile ./profile \
            --no-write-lock-file \
            -v --show-trace --print-build-logs \
            --log-format raw \
             > >(tee stdout.log) 2> >(tee /tmp/nix-build-err.log >&2)

      - name: Build new ${{ matrix.system }} system
        run: |
          set -o pipefail
          nix build \
            ".#ciSystems.${{ matrix.system }}" \
            --profile ./profile \
            --no-write-lock-file \
            --fallback \
            -v --show-trace --print-build-logs \
            --log-format raw \
             > >(tee stdout.log) 2> >(tee /tmp/nix-build-err.log >&2) | cachix push soulwhisper

      - name: Show drv failure details
        if: failure()
        run: |
          failed_drv_t1=$(grep "For full logs" /tmp/nix-build-err.log | grep -oE "/nix/store/.*.drv")
          failed_drv_t2=$(grep "failed to build" /tmp/nix-build-err.log | grep -oE "/nix/store/.*.drv" | head -n 1 )
          echo "Last 100 lines of error log:"
          tail -n 100 /tmp/nix-build-err.log
          if [ -n $failed_drv_t1]; then
            nix log $failed_drv_t1
          else if [ -n $failed_drv_t2]; then
            nix log $failed_drv_t2
          fi
          exit 1

      - name: Diff profile
        id: diff
        run: |
          nix profile diff-closures --profile ./profile
          delimiter="$(openssl rand -hex 16)"
          echo "diff<<${delimiter}" >> "${GITHUB_OUTPUT}"
          nix profile diff-closures --profile ./profile | perl -pe 's/\e\[[0-9;]*m(?:\e\[K)?//g' >> "${GITHUB_OUTPUT}"
          echo "${delimiter}" >> "${GITHUB_OUTPUT}"

      - name: Generate Token
        uses: actions/create-github-app-token@0d564482f06ca65fa9e77e2510873638c82206f2 # v1
        id: app-token
        with:
          app-id: ${{ secrets.LAB_ASSISTANT_APP_ID }}
          private-key: ${{ secrets.LAB_ASSISTANT_APP_KEY }}

      - name: Comment report in pr
        uses: marocchino/sticky-pull-request-comment@52423e01640425a022ef5fd42c6fb5f633a02728 # v2
        with:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
          header: ".#ciSystems.${{ matrix.system }}"
          message: |
            ### Report for `${{ matrix.system }}`

            <summary> Version changes </summary> <br>
            <pre> ${{ steps.diff.outputs.diff }} </pre>

  sync-stable:
    if: ${{ !cancelled() }}
    needs:
      - nix-build
    runs-on: ubuntu-latest
    steps:
      - name: Check build matrix status
        if: ${{ needs.nix-build.result != 'success' }}
        run: exit 1
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: main
          fetch-depth: 0
      - name: Generate Token
        uses: actions/create-github-app-token@0d564482f06ca65fa9e77e2510873638c82206f2 # v1
        id: app-token
        with:
          app-id: ${{ secrets.LAB_ASSISTANT_APP_ID }}
          private-key: ${{ secrets.LAB_ASSISTANT_APP_KEY }}
      - name: Sync stable
        uses: devmasx/merge-branch@master
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          type: now
          from_branch: main
          target_branch: stable
