name: Schedule - Cleanup

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      days:
        description: 'Days-worth of runs to keep for each workflow'
        required: true
        default: '2'
      minimum_runs:
        description: 'Minimum runs to keep for each workflow'
        required: true
        default: '10'
      delete_workflow_by_state_pattern:
        description: 'Filter workflows by state: active, deleted, disabled_fork, disabled_inactivity, disabled_manually'
        required: true
        default: "ALL"
        type: choice
        options:
          - "ALL"
          - active
          - deleted
          - disabled_inactivity
          - disabled_manually
      delete_run_by_conclusion_pattern:
        description: 'Remove runs based on conclusion: action_required, cancelled, failure, skipped, success'
        required: true
        default: "ALL"
        type: choice
        options:
          - "ALL"
          - "Unsuccessful: action_required,cancelled,failure,skipped"
          - action_required
          - cancelled
          - failure
          - skipped
          - success

jobs:
  cleanup_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1
        id: app-token
        with:
          app-id: ${{ secrets.LAB_ASSISTANT_APP_ID }}
          private-key: ${{ secrets.LAB_ASSISTANT_APP_KEY }}

      - name: Cleanup workflow stale runs
        uses: Mattraks/delete-workflow-runs@4c9f24749b7996562658e3d6e10662489e22caca # v2
        with:
          token: "${{ steps.app-token.outputs.token }}"
          repository: "${{ github.repository }}"
          retain_days: "0"
          keep_minimum_runs: "0"
          delete_run_by_conclusion_pattern: "cancelled,skipped"

      - name: Cleanup workflow success runs
        uses: Mattraks/delete-workflow-runs@4c9f24749b7996562658e3d6e10662489e22caca # v2
        with:
          token: "${{ steps.app-token.outputs.token }}"
          repository: "${{ github.repository }}"
          retain_days: "7"
          keep_minimum_runs: "10"
          delete_run_by_conclusion_pattern: "success"


      - name: Clenaup workflow "update-nvfetcher" runs
        uses: Mattraks/delete-workflow-runs@4c9f24749b7996562658e3d6e10662489e22caca # v2
        with:
          token: "${{ steps.app-token.outputs.token }}"
          repository: "${{ github.repository }}"
          retain_days: "1"
          keep_minimum_runs: "10"
          delete_workflow_pattern: "update-nvfetcher.yml"
