---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Schedule - Cleanup

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  cleanup_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.PRIVATE_APP_ID }}
          private-key: ${{ secrets.PRIVATE_APP_KEY }}

      - name: Cleanup workflow stale runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: "${{ steps.app-token.outputs.token }}"
          repository: "${{ github.repository }}"
          retain_days: "0"
          keep_minimum_runs: "0"
          delete_run_by_conclusion_pattern: "cancelled,skipped"

      - name: Cleanup workflow success runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: "${{ steps.app-token.outputs.token }}"
          repository: "${{ github.repository }}"
          retain_days: "0"
          keep_minimum_runs: "5"
          delete_run_by_conclusion_pattern: "success"

      - name: Clenaup workflow failure runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: "${{ steps.app-token.outputs.token }}"
          repository: "${{ github.repository }}"
          retain_days: "0"
          keep_minimum_runs: "3"
          delete_run_by_conclusion_pattern: "action_required,failure"
