---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Update flake

# this workflow enabled since renovate broken,
# with specific token, this action will trigger other workflow runs (nix-build).

on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 1 * * *

permissions:
  contents: write
  pull-requests: write

jobs:
  update-flakes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d # v16
      - name: Generate Token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1
        id: app-token
        with:
          app-id: ${{ secrets.LAB_ASSISTANT_APP_ID }}
          private-key: ${{ secrets.LAB_ASSISTANT_APP_KEY }}
      - name: Update flakes
        id: update-flakes
        uses: DeterminateSystems/update-flake-lock@a2bbe0274e3a0c4194390a1e445f734c597ebc37 # v24
        with:
          token: ${{ steps.app-token.outputs.token }}
          pr-title: "chore(deps): Update flakes lockfile"
          git-author-name: '${{ steps.app-token.outputs.app-slug }}[bot]'
          git-author-email: '${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
          git-committer-name: '${{ steps.app-token.outputs.app-slug }}[bot]'
          git-committer-email: '${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
