---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Update flake

# this workflow enabled since renovate broken,
# with specific token, this action will trigger other workflow runs (nix-build).

on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 1 * * *

permissions:
  contents: write
  pull-requests: write

jobs:
  update-flakes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v20
        with:
          extra-args: --prefer-upstream-nix
      - name: Generate Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.PRIVATE_APP_ID }}
          private-key: ${{ secrets.PRIVATE_APP_KEY }}
      - name: Update flakes
        id: update-flakes
        uses: DeterminateSystems/update-flake-lock@v25
        with:
          token: ${{ steps.app-token.outputs.token }}
          pr-title: "chore(deps): Update flakes lockfile"
          commit-msg: "chore(deps): Update flakes lockfile"
          git-author-name: "${{ steps.app-token.outputs.app-slug }}[bot]"
          git-author-email: "${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com"
          git-committer-name: "${{ steps.app-token.outputs.app-slug }}[bot]"
          git-committer-email: "${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com"
