name: Update nvfetcher
on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 * * * *
  push:
    branches:
      - main
    paths:
      - pkgs/nvfetcher.toml
jobs:
  update-nvfetcher:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d # v16
      - name: Run nvfetcher
        id: run-nvfetcher
        run: |
          cd pkgs
          nix-shell -p nvfetcher --command 'nvfetcher -l /tmp/nvfetcher-changes'
          {
            echo 'changes<<EOF'
            cat /tmp/nvfetcher-changes
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Update caddy-custom
        id: update-caddy-custom
        run: |
          if grep -q "caddy" "/tmp/nvfetcher-changes"; then
            echo "Updating caddy-custom ..."
            updateInfo() {
              version=$(sed -n 's#.*github.com/caddyserver/caddy/v2 \(.*\)#\1#p' "caddy-custom/src/go.mod")
              cfVersion=$(sed -n 's#.*github.com/caddy-dns/cloudflare \(.*\)#\1#p' "caddy-custom/src/go.mod")
              dist_hash=$(nix-prefetch-github caddyserver dist --rev "$version" | jq -r .hash)
              {
                echo '# This file was autogenerated. DO NOT EDIT!'
                echo '{'
                echo "  version = \"$version\";"
                echo "  cfVersion = \"$cfVersion\";"
                echo "  vendorHash = \"$1\";"
                echo "  dist = {"
                echo "    owner = \"caddyserver\";"
                echo "    repo = \"dist\";"
                echo "    rev = \"$version\";"
                echo "    hash = \"$dist_hash\";"
                echo "  };"
                echo '}'
              } >"caddy-custom/src/src.nix"
            }

            cd caddy-custom/src
            rm go*
            go mod init caddy
            go mod tidy
            updateInfo ""
            vendor_hash="$(nix build ../../../.#caddy-custom |& sed -n 's/.*got: *//p')"
            updateInfo "$vendor_hash"
            echo "... completed."
          fi

      - name: Update vendorHash
        id: update-vendorhash
        run: |
          setHash () {
            jq --arg app "${1}" --arg hash "${2}" '.[$app] = $hash' pkgs/_sources/vendorhash.json > tmp.json
            mv tmp.json pkgs/_sources/vendorhash.json
          }

          declare -a APP_NAMES
          while read line; do
            APP_NAMES+=("${line%:*}")
          done < /tmp/nvfetcher-changes

          for APP_NAME in "${APP_NAMES[@]}"; do
            echo "Check vendorHash for ${APP_NAME}..."
            setHash "${APP_NAME}" ""
            vendorHash=$(nix build --no-link .#${APP_NAME} 2>&1 >/dev/null | grep "got:" | cut -d':' -f2 | sed 's| ||g')

            if [[ -n "${vendorHash}" ]]; then
              setHash "${APP_NAME}" "${vendorHash}"
              echo "Updated ${APP_NAME} with vendorHash: ${vendorHash}"
            fi
          done

      - name: Generate Token
        uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1
        id: app-token
        with:
          app-id: ${{ secrets.LAB_ASSISTANT_APP_ID }}
          private-key: ${{ secrets.LAB_ASSISTANT_APP_KEY }}
      - name: Create Pull Request
        id: create-pull-request
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7
        with:
          token: ${{ steps.app-token.outputs.token }}
          title: "chore(deps): Update packages managed by nvfetcher"
          commit-message: "chore(deps): Update packages managed by nvfetcher"
          body: |
            ## Changes:
            ## ${{ steps.run-nvfetcher.outputs.changes }}
          add-paths: |
            pkgs/**
          delete-branch: true
      # - name: Automerge Pull Request
      #   if: steps.create-pull-request.outputs.pull-request-operation == 'created' || steps.create-pull-request.outputs.pull-request-operation == 'updated'
      #   run: gh pr merge --auto --squash --delete-branch ${{ steps.create-pull-request.outputs.pull-request-number }}
      #   env:
      #     GH_TOKEN: ${{ steps.app-token.outputs.token }}
