name: Update nvfetcher
on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 * * * *
  push:
    branches:
      - main
    paths:
      - pkgs/nvfetcher.toml
jobs:
  update-nvfetcher:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@da36cb69b1c3247ad7a1f931ebfd954a1105ef14 # v14
      - name: Run nvfetcher
        id: run-nvfetcher
        run: |
          cd pkgs
          {
            echo 'changes<<EOF'
            nix-shell -p nvfetcher --command 'nvfetcher' | sed -n '/Changes/,/$!d/p'
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"
      - name: Generate Token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1
        id: app-token
        with:
          app-id: ${{ secrets.LAB_ASSISTANT_APP_ID }}
          private-key: ${{ secrets.LAB_ASSISTANT_APP_KEY }}
      - name: Create Pull Request
        id: create-pull-request
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7
        with:
          token: ${{ steps.app-token.outputs.token }}
          title: "chore(deps): Update packages managed by nvfetcher"
          commit-message: "chore(deps): Update packages managed by nvfetcher"
          body: |
            ## ${{ steps.run-nvfetcher.outputs.changes }}
          add-paths: |
            pkgs/**
          delete-branch: true
      - name: Automerge Pull Request
        run: gh pr merge --auto --squash --delete-branch ${{ steps.create-pull-request.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
